---
title: "Module 8: Wrangling"
author: "Nicole Luisi"
date: "`r Sys.Date()`"
output: html_document
---

This Quarto file was developed for the MADA Module 8 exercise.

### **Load and Process Data**

##### **Load required packages**

```{r}
#| warning: false
library("here")
library("tidyverse")
```

##### **Load data**

```{r}
# Note: Ignore extension on file, actually an RDS file 
mod8 <- readRDS(here("fluanalysis", "data", "SympAct_Any_Pos.Rda"))
```

##### **Remove all variables that have Score or Total or FluA or FluB or Dxname or Activity in their name**

```{r}
names(mod8) #n=63 vars
mod8_1 <- mod8 %>% dplyr:: select(-matches("Score|Total|FluA|FluB|Dxname|Activity"))
names(mod8_1) #n=33 vars
```

##### **Also remove the variable `Unique.Visit`**
```{r}
mod8_2 <- mod8_1 %>% dplyr:: select(-Unique.Visit) #n=32 vars
```

##### **Remove any NA observations**

```{r}
mod8_3 <- na.omit(mod8_2) #n=730 obs
```

##### **Save new RDS file**

```{r}
saveRDS(mod8_3, (here("fluanalysis", "data", "mod8_clean.rds")))
```


